service: iot-serverless

custom:
  stage: ${opt:stage, self:provider.stage}
  serviceName: iot_serverless
  S3BucketNameForKinesisDestination: ${self:service}-${self:custom.stage}-kinesis-destination

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - sts:AssumeRole

functions:
  hello:
    handler: handler.hello
  transform:
    handler: handler.transform
    name: ${self:service}-${self:custom.stage}-data-transform-lambda
    timeout: 60

#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/kinesis.yml)}
  - ${file(resources/iot-core.yml)}
